In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [10]:
df = pd.read_csv("../data/screentime_and_stress.csv")
df.shape

(15000, 13)

In [11]:
df.sample(5)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
2483,2484,20,Female,Software Engineer,6.54,58,6.48,6.91,6.54,3,76,93,6.31
6955,6956,53,Female,Teacher,5.49,118,6.88,5.46,7.65,1,76,180,6.71
4098,4099,20,Female,Doctor,9.52,15,5.79,5.77,9.79,0,26,30,8.01
9898,9899,53,Male,Manager,3.59,53,6.87,7.25,4.67,1,9,48,6.12
1915,1916,35,Female,Student,9.86,38,4.12,3.82,10.00,4,46,245,9.65

In [12]:
df.isnull().sum()

user_id                             0
age                                 0
gender                              0
occupation                          0
daily_screen_time_hours             0
phone_usage_before_sleep_minutes    0
sleep_duration_hours                0
sleep_quality_score                 0
stress_level                        0
caffeine_intake_cups                0
physical_activity_minutes           0
notifications_received_per_day      0
mental_fatigue_score                0
dtype: int64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15000 non-null  int64
 1   age                               15000 non-null  int64
 2   gender                            15000 non-null  str
 3   occupation                        15000 non-null  str
 4   daily_screen_time_hours           15000 non-null  float64
 5   phone_usage_before_sleep_minutes  15000 non-null  int64
 6   sleep_duration_hours              15000 non-null  float64
 7   sleep_quality_score               15000 non-null  float64
 8   stress_level                      15000 non-null  float64
 9   caffeine_intake_cups              15000 non-null  int64
 10  physical_activity_minutes         15000 non-null  int64
 11  notifications_received_per_day    15000 non-null  int64
 12  mental_fatigue_score              15000 non-null  float64
dtypes: float64(5), int64(6), str(2)
memory usage: 1.5 MB

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.corr(numeric_only=True)

,user_id,age,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
user_id,1.000000,-0.009833,0.010960,-0.003865,-0.014394,-0.004342,0.009981,0.003379,0.000799,-0.003432,0.005458
age,-0.009833,1.000000,0.009094,-0.007754,-0.005847,-0.000466,0.002849,-0.019182,-0.005827,-0.001594,0.009724
daily_screen_time_hours,0.010960,0.009094,1.000000,0.004228,-0.001838,-0.746531,0.879001,0.006128,0.002899,-0.003357,0.828368
phone_usage_before_sleep_minutes,-0.003865,-0.007754,0.004228,1.000000,-0.012930,-0.335283,0.155330,0.004639,-0.012705,-0.000691,0.150180
sleep_duration_hours,-0.014394,-0.005847,-0.001838,-0.012930,1.000000,0.009990,-0.004893,-0.013682,-0.001118,0.005343,-0.011073
sleep_quality_score,-0.004342,-0.000466,-0.746531,-0.335283,0.009990,1.000000,-0.857463,-0.009033,-0.005857,0.003354,-0.808019
stress_level,0.009981,0.002849,0.879001,0.155330,-0.004893,-0.857463,1.000000,0.003458,0.009360,-0.002808,0.948768
caffeine_intake_cups,0.003379,-0.019182,0.006128,0.004639,-0.013682,-0.009033,0.003458,1.000000,0.010249,0.006762,-0.002722
physical_activity_minutes,0.000799,-0.005827,0.002899,-0.012705,-0.001118,-0.005857,0.009360,0.010249,1.000000,0.006069,0.010254
notifications_received_per_day,-0.003432,-0.001594,-0.003357,-0.000691,0.005343,0.003354,-0.002808,0.006762,0.006069,1.000000,-0.005077
mental_fatigue_score,0.005458,0.009724,0.828368,0.150180,-0.011073,-0.808019,0.948768,-0.002722,0.010254,-0.005077,1.000000